/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KZA BYOD
 */
import java.awt.event.*;
import java.awt.*;

public class TestTickle extends javax.swing.JFrame {
    
 //Method to close jframe
    public void close(){
       WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * Creates new form TestTickle
     */
    public TestTickle() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1015, 501));

        jButton1.setText("Bevestigen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geschiktheid", "Prestatie-efficiëntie", "Uitwisselbaarheid", "Bruikbaarheid", "Betrouwbaarheid", "Beveiligbaarheid", "Onderhoudbaarheid", "Overdraagbaarheid", "Effectiviteit", "Efficiëntie", "Voldoening", "Vrijwaring tegen risico's", "Contextdekking" }));

        jButton2.setText("Main");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Kies een kwaliteitsattribuut:");

        jButton3.setText("Internet");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String geschiktheid;
        String prestatieefficiency;
        String uitwisselbaarheid;
        String bruikbaarheid;
        String betrouwbaarheid;
        String beveiligbaarheid;
        String onderhoudbaarheid; 
        String overdraagbaarheid;
        String effectiviteit;
        String efficiency;
        String voldoening;
        String vrijwaringTegenRisicos;
        String contextdekking;
               
        geschiktheid = "<html><p>De mate waarin een softwareproduct of computersysteem functies levert die voldoen aan de uitgesproken" +
                        "en veronderstelde behoeften, bij gebruik onder gespecificeerde condities. <br>"+
                        "<b>Functionele compleetheid (Functional completeness)</b><br>"+
                        "De mate waarin de set van functies alle gespecificeerde taken en gebruikersdoelen ondersteunen.<br>"+
                        "<b>Functionele correctheid (Functional correctness)</b><br>"+
                        "De mate waarin een softwareproduct of computersysteem de juiste resultaten met de benodigde nauwkeurigheid beschikbaar stelt.<br>"+
                        "<b>Functionele toepasselijkheid (Functional appropriateness)</b><br>"+
                        "De mate waarin de functies bijdragen aan het behalen van specifieke taken en doelen.</p></html>";
        prestatieefficiency = "<html><p>De prestaties in verhouding tot de hoeveelheid middelen gebruikt onder genoemde condities.<br>" +
                        "<b>Snelheid (Time-behaviour)</b><br>" +
                        "De mate waarin antwoord- en verwerkingstijden en doorvoersnelheid van een product of systeem, tijdens de uitvoer van zijn functies, voldoet aan de wensen.<br>" +
                        "<b>Middelenbeslag (Resource utilization)</b><br>" +
                        "De mate waarin de hoeveelheid en type middelen die gebruikt worden door een product of systeem, tijdens de uitvoer van zijn functies, voldoet aan de wensen.<br>" +
                        "<b>Capaciteit (Capacity)</b><br>" +
                        "De mate waarin de maximale limieten van een product- of systeemparameter voldoet aan de wensen.</p></html>";
        uitwisselbaarheid = "<html><p>De mate waarin een product, systeem of component informatie uit kan wisselen met andere producten, systemen of componenten, en/of het de gewenste functies kan uitvoeren terwijl het dezelfde hard- of software-omgeving deelt.<br>" +
                        "<b>Beïnvloedbaarheid (Co-existence)</b><br>" +
                        "De mate waarin een product zijn gewenste functies efficiënt kan uitvoeren terwijl het een gemeenschappelijke omgeving en middelen deelt met andere producten, zonder nadelige invloed op enig ander product.<br>" +
                        "<b>Koppelbaarheid (Interoperability)</b><br>" +
                        "De mate waarin twee of meer systemen, producten of componenten informatie kunnen uitwisselen en de uitgewisselde informatie kunnen gebruiken.</html></p>";
        bruikbaarheid = "<html><p>De mate waarin een product of systeem gebruikt kan worden door gespecificeerde gebruikers om effectief, efficiënt en naar tevredenheid gespecificeerde doelen te bereiken in een gespecificeerde gebruikscontext.<br>" +
                        "<b>Herkenbaarheid van geschiktheid (Appropriateness recognisability)</b><br>" +
                        "De mate waarin gebruikers kunnen herkennen of een product of systeem geschikt is voor hun behoeften.<br>" +
                        "<b>Leerbaarheid (Learnability)</b><br>" +
                        "De mate waarin een product of systeem gebruikt kan worden door gespecificeerde gebruikers om gespecificeerde leerdoelen te bereiken met betrekking tot het gebruik van het product of systeem met effectiviteit, efficiëntie, vrijheid van risico en voldoening, in een gespecificeerde gebruikscontext.<br>" +
                        "<b>Bedienbaarheid (Operability)</b><br>" +
                        "De mate waarin een product of systeem attributen heeft die het makkelijk maken om het te bedienen en beheersen.<br>" +
                        "<b>Voorkomen gebruikersfouten (User error protection)</b><br>" +
                        "De mate waarin het systeem gebruikers beschermt tegen het maken van fouten.<br>" +
                        "<b>Volmaaktheid gebruikersinteractie (User interface aesthetics)</b><br>" +
                        "De mate waarin een gebruikersinterface het de gebruiker mogelijk maakt om een plezierige en voldoening gevende interactie te hebben.<br>" +
                        "<b>Toegankelijkheid (Accessibility)</b><br>" +
                        "De mate waarin een product of systeem gebruikt kan worden door mensen met de meest uiteenlopende eigenschappen en mogelijkheden om een gespecificeerd doel te bereiken in een gespecificeerde gebruikscontext</p></html>";
        betrouwbaarheid = "<html><p>De mate waarin een systeem, product of component gespecificeerde functies uitvoert onder gespecificeerde condities gedurende een gespecificeerde hoeveelheid tijd.<br>" +
                        "<b>Volwassenheid (Maturity)</b><br>" +
                        "De mate waarin een systeem, product of component aan betrouwbaarheidsbehoeften voldoet onder normale werkomstandigheden.<br>" +
                        "<b>Beschikbaarheid (Availability)</b><br>" +
                        "De mate waarin een systeem, product of component operationeel en toegankelijk is wanneer men het wil gebruiken.<br>" +
                        "<b>Foutbestendigheid (Fault tolerance)</b><br>" +
                        "De mate waarin een systeem, product of component werkt zoals bedoeld ondanks de aanwezigheid van hard- of softwarefouten.<br>" +
                        "<b>Herstelbaarheid (Recoverability)</b><br>" +
                        "De mate waarin het product of systeem, in geval van een onderbreking of bij een fout, de direct betrokken gegevens kan herstellen en het systeem in de gewenste staat kan terug brengen.</p></html>";
        beveiligbaarheid = "<html><p>De mate waarin een product of systeem informatie en gegevens beschermt zodat personen, andere producten of systemen de juiste mate van gegevenstoegang hebben passend bij hun soort en niveau van autorisatie.<br>" +
                        "<b>Vertrouwelijkheid (Confidentiality)</b><br>" +
                        "De mate waarin een product of systeem ervoor zorgt dat gegevens alleen toegankelijk zijn voor diegenen die geautoriseerd zijn.<br>" +
                        "<b>Integriteit (Integrity)</b><br>" +
                        "De mate waarin een systeem, product of component ongeautoriseerde toegang tot of aanpassing van computerprogramma’s of gegevens verhindert.<br>" +
                        "<b>Onweerlegbaarheid (Non-repudiation)</b><br>" +
                        "De mate waarin kan worden bewezen dat acties of gebeurtenissen plaats hebben gevonden, zodat later deze acties of gebeurtenissen niet ontkend kunnen worden.<br>" +
                        "<b>Verantwoording (Accountability)</b><br>" +
                        "De mate waarin acties van een entiteit getraceerd kunnen worden naar die specifieke entiteit.<br>" +
                        "<b>Authenticiteit (Authenticity)</b><br>" +
                        "De mate waarin bewezen kan worden dat de identiteit van een onderwerp of bron is zoals wordt beweerd.<br>" +
                        "De mate waarin een claim over de oorsprong of de auteur van de informatie verifieerbaar is, bijvoorbeeld aan handschrift.</p></html>";
        onderhoudbaarheid = "<html><p>De mate waarin een product of systeem effectief en efficiënt gewijzigd kan worden door de aangewezen beheerders.<br>" +
                        "<b>Modulariteit (Modularity)</b><br>" +
                        "De mate waarin een systeem of computerprogramma opgebouwd is in losstaande componenten zodat wijzigingen van een component minimale impact heeft op andere componenten.<br>" +
                        "<b>Herbruikbaarheid (Reusability)</b><br>" +
                        "De mate waarin een bestaand onderdeel gebruikt kan worden in meer dan één systeem of bij het bouwen van een nieuw onderdeel.<br>" +
                        "<b>Analyseerbaarheid (Analysability)</b><br>" +
                        "De mate waarin het mogelijk is om effectief en efficiënt de impact, van een geplande verandering van één of meer onderdelen, op een product of systeem te beoordelen, om afwijkingen en/of foutoorzaken van een product vast te stellen of om onderdelen te identificeren die gewijzigd moeten worden.<br>" +
                        "<b>Wijzigbaarheid (Modifiability)</b><br>" +
                        "De mate waarin een product of systeem effectief en efficiënt gewijzigd kan worden zonder fouten of kwaliteitsvermindering tot gevolg.<br>" +
                        "<b>Testbaarheid (Testability)</b><br>" +
                        "De mate waarin effectief en efficiënt testcriteria vastgesteld kunnen worden voor een systeem, product of component en waarin tests uitgevoerd kunnen worden om vast te stellen of aan die criteria is voldaan.</p></html>";
        overdraagbaarheid = "<html><p>De mate waarin een systeem, product of component effectief en efficiënt overgezet kan worden van één hardware, software of andere operationele of gebruiksomgeving naar een andere.<br>" +
                        "<b>Aanpasbaarheid (Adaptability)</b><br>" +
                        "De mate waarin een product of systeem effectief en efficiënt aangepast kan worden voor andere of zich ontwikkelende hardware, software of andere operationele of gebruiksomgevingen.<br>" +
                        "<b>Installeerbaarheid (Installability)</b><br>" +
                        "De mate waarin het product of het systeem effectief en efficiënt geïnstalleerd of verwijderd kan worden in een gespecificeerde omgeving.<br>" +
                        "<b>Vervangbaarheid (Replaceability)</b><br>" +
                        "De mate waarin een product een ander specifiek softwareproduct, met hetzelfde doel in de zelfde omgeving, kan vervangen.</p></html>";
        effectiviteit = "<html><p>De nauwkeurigheid en volledigheid waarmee gebruikers gespecificeerde doelen behalen.</p></html>";
        efficiency = "<html><p>De benodigde hulpbronnen die gebruikt zijn in verhouding tot de nauwkeurigheid en volledigheid waarmee gebruikers doelen behalen.</p></html>";
        voldoening = "<html><p>De mate waarin gebruikersbehoeften vervuld worden als het product of systeem gebruikt wordt in een gespecificeerde gebruikscontext.<br>" +
                        "<b>Bruikbaarheid (Usefullness)</b><br>" +
                        "De mate waarin een gebruiker tevreden is met de voor de gebruiker waargenomen behaalde doelen, inclusief de resultaten van het gebruik van het systeem en de consequenties van het gebruik van het systeem.<br>" +
                        "<b>Vertrouwen (Trust)</b><br>" +
                        "De mate waarin een gebruiker of andere betrokkene vertrouwen heeft dat het product of systeem zich zal gedragen zoals bedoeld.<br>" +
                        "<b>Tevredenheid (Pleasure)</b><br>" +
                        "De mate waarin een gebruiker tevreden is bij het verwezenlijken van zijn persoonlijke wensen.<br>" +
                        "<b>Welzijn (Comfort)</b><br>" +
                        "De mate waarin een gebruiker tevreden is met zijn fysiek welzijn.</p></html>";
        vrijwaringTegenRisicos = "<html><p>De mate waarin een product of systeem het potentiële risico beperkt met betrekking tot economische status, mensenlevens, gezondheid of de omgeving.<br>" +
                        "<b>Economisch risico beperking (Economic risk mitigation)</b><br>" +
                        "De mate waarin een product of systeem de potentiële risico’s beperkt met betrekking tot financiële status, efficiënte werking, commerciële eigendommen, reputatie of andere middelen in de beoogde gebruikscontexten.<br>" +
                        "<b>Gezond- en veiligheidsrisico beperking (Health and safety risk mitigation)</b><br>" +
                        "De mate waarin een product of systeem de potentiële risico’s met betrekking tot personen beperkt in de beoogde gebruikscontexten.<br>" +
                        "<b>Omgevingsrisico beperking (Environmental risk mitigation)</b><br>" +
                        "De mate waarin een product of systeem de potentiële risico’s met betrekking tot eigendommen of de omgeving beperkt in de beoogde gebruikscontexten.</p></html>";
        contextdekking = "<html><p>De mate waarin een product of systeem gebruikt kan worden met effectiviteit, efficiëntie, vrijheid van risico en voldoening zowel in de gespecificeerde gebruikscontexten als in niet initieel gespecificeerde gebruikscontexten.<br>" +
                        "<b>Context compleetheid (Context completeness)</b><br>" +
                        "De mate waarin een product of systeem gebruikt kan worden met effectiviteit, efficiëntie, vrijheid van risico en voldoening in alle gespecificeerde gebruikscontexten.<br>" +
                        "<b>Flexibiliteit (Flexibility)</b><br>" +
                        "De mate waarin een product of systeem gebruikt kan worden met effectiviteit, efficiëntie, vrijheid van risico en voldoening in gebruikscontexten die niet initieel gespecificeerd zijn in de requirements.</p></html>";
        String  waarde; 
        waarde = jComboBox1.getSelectedItem().toString();
        if(waarde == "Geschiktheid"){
            jLabel3.setText(geschiktheid);
        } else if (waarde == "Prestatie-efficiëntie"){ 
            jLabel3.setText(prestatieefficiency);
        } else if (waarde == "Uitwisselbaarheid"){
            jLabel3.setText(uitwisselbaarheid);
        } else if (waarde == "Bruikbaarheid"){
            jLabel3.setText(bruikbaarheid);
        } else if (waarde == "Betrouwbaarheid"){
            jLabel3.setText(betrouwbaarheid);
        } else if (waarde == "Beveiligbaarheid") {
            jLabel3.setText(beveiligbaarheid);
        } else if (waarde == "Onderhoudbaarheid"){
            jLabel3.setText(onderhoudbaarheid);
        } else if (waarde == "Overdraagbaarheid"){
            jLabel3.setText(overdraagbaarheid);
        } else if (waarde == "Effectiviteit"){
            jLabel3.setText(effectiviteit);
        } else if (waarde == "Efficiëntie"){
            jLabel3.setText(efficiency);
        } else if (waarde == "Voldoening"){
            jLabel3.setText(voldoening);
        } else if (waarde == "Vrijwaring tegen risico's"){
            jLabel3.setText(vrijwaringTegenRisicos);
        } else {
           jLabel3.setText(contextdekking);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
      
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Main gui = new Main();
               gui.setVisible(true);
     TestTickle gui2 = new TestTickle();
               close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String waarde2;
waarde2 = jComboBox1.getSelectedItem().toString();
        if(waarde2 == "Geschiktheid"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Geschiktheid_.28Functional_suitability.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
                }
    }//GEN-LAST:event_jButton3ActionPerformed
        else if(waarde2 == "Prestatie-efficiëntie"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Prestatie-effici.C3.ABntie_.28Performance_efficiency.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }        
        else if(waarde2 == "Uitwisselbaarheid"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Uitwisselbaarheid_.28Compatibility.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }      
        else if(waarde2 == "Bruikbaarheid"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Bruikbaarheid_.28Usability.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }         
        else if(waarde2 == "Betrouwbaarheid"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Betrouwbaarheid_.28Reliability.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }         
        else if(waarde2 == "Beveiligbaarheid"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Beveiligbaarheid_.28Security.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }         
        else if(waarde2 == "Onderhoudbaarheid"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Onderhoudbaarheid_.28Maintainability.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }       
        else if(waarde2 == "Overdraagbaarheid"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Overdraagbaarheid_.28Portability.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }   
        else if(waarde2 == "Effectiviteit"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Effectiviteit_.28Effectiveness.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }   
        else if(waarde2 == "Efficiëntie"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Effici.C3.ABntie_.28Efficiency.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }   
        else if(waarde2 == "Voldoening"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Voldoening_.28Satisfaction.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }   
        else if(waarde2 == "Vrijwaring tegen risico's"){
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Vrijwaring_tegen_risico_.28Freedom_from_risk.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }   
        else {
        try{

                String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://nl.wikipedia.org/wiki/ISO_25010#Context_dekking_.28Context_coverage.29" ;

                Process link = Runtime.getRuntime().exec(command);
            }
                catch(Exception ex){
                System.out.println("cannot execute command. " +ex);
    }
    }   
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestTickle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestTickle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestTickle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestTickle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestTickle().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}

